spring:
  profiles:
    active: dev2
  application:
    name: gateway-server
  mybatis-plus:
    mapper-locations: classpath:mapper/*.xml
    type-aliases-package: com.acimage.common.model.domain
    global-config:
      db-config:
        table-prefix: tb_
  cloud:
    gateway:
      routes:
        - id: community-service-route
          uri: lb://community-service
          predicates:
            - Path=/api/community/**

        - id: image-service-route
          uri: lb://image-service
          predicates:
            - Path=/api/image/**

        - id: user-service-route
          uri: lb://user-service
          predicates:
            - Path=/api/user/**

        - id: admin-service-route
          uri: lb://admin-service
          predicates:
            - Path=/api/admin/**
      filters:
        - name: RequestRateLimiter
          args:
            redis-rate-limiter.replenishRate: 20 #补充速率
            redis-rate-limiter.burstCapacity: 30 #桶容量
            key-resolver: "#{@ipKeyResolver}" #这个必须要配置，否则返回403



ignore:
  urls:
    - /api/community/topics/recentHot
    - /api/community/topics/recommend
    - /api/community/topics/info/*
    - /api/community/users/rank/**
    - /api/image/spImages/homeCarousel
    - /api/user/logins/**
    - /api/user/users/isExist/**
    - /api/user/verifies/**


