spring:
  profiles:
    include: common,common-secret
    active: dev2

  application:
    name: gateway-server
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
  cloud:
    gateway:
      routes:
        - id: community-service-route
          uri: lb://community-service
          predicates:
            - Path=/api/community/**

        - id: image-service-route
          uri: lb://image-service
          predicates:
            - Path=/api/image/**

        - id: user-service-route
          uri: lb://user-service
          predicates:
            - Path=/api/user/**

        - id: admin-service-route
          uri: lb://admin-service
          predicates:
            - Path=/api/admin/**
      filters:
        - name: RequestRateLimiter
          args:
            redis-rate-limiter.replenishRate: 20 #补充速率
            redis-rate-limiter.burstCapacity: 30 #桶容量
            key-resolver: "#{@ipKeyResolver}" #这个必须要配置，否则返回403

mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.acimage.common.model.domain
  type-handlers-package: com.acimage.common.config.typehandler
  global-config:
    db-config:
      table-prefix: tb_

role:
  visitorId: 2
  userId: 1


