server:
  port: 8070

spring:
  config:
    activate:
      on-profile:
        - dev
  redis:
    host: 192.168.130.128
    port: 6379
    password: redis
    lettuce:
      pool:
        max-active: 8
        max-idle: 8 #最大空闲连接
        min-idle: 0 #最小空闲连接
        max-wait: 100ms #连接等待时间

