server:
  port: 8090

spring:
  config:
    activate:
      on-profile:
        - dev
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/acimage_image?useSSl=false&allowMultiQueries=true&serverTimezone=UTC
    username: root
    password: mysql
  rabbitmq:
    host: 192.168.130.128
    port: 5672
    username: acimage
    password: acimage
    virtual-host: /acimage
    listener:
      simple:
        acknowledge-mode: manual # 手动应答
        auto-startup: false #消费者是否自动启动
        prefetch: 1 #每次从队列中取一个,轮询分发，默认是公平分发
        retry:
          max-attempts: 5 # 重试次数
          enabled: true # 开启重试
      direct:
        auto-startup: false #生产者是否自动启动
        acknowledge-mode: manual # 手动应答
  redis:
    host: 192.168.130.128
    port: 6379
    password: redis
    lettuce:
      pool:
        max-active: 30
        max-idle: 8 #最大空闲连接
        min-idle: 0 #最小空闲连接
        max-wait: 100ms #连接等待时间
  cloud:
    nacos:
      server-addr: localhost:8848 #nacos 服务地址
