spring:
  profiles:
    include: common,common-secret
    active: dev2
  application:
    name: image-service
  servlet:
    multipart:
      max-file-size: 2MB
      max-request-size: 4MB

feign:
  okhttp:
    enabled: true
  httpclient:
    max-connections: 20 # 最大的连接数
    max-connections-per-route: 5 # 每个路径的最大连接数

mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.acimage.image.model.domain,com.acimage.common.model.domain
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.slf4j.Slf4jImpl
  global-config:
    db-config:
      table-prefix: tb_


