
spring:
  mvc:
    hiddenmethod:
      filter:
        enabled: true
  redis:
    host: 192.168.130.128
    port: 6379
    password: redis
    lettuce:
      pool:
        max-active: 8
        max-idle: 8 #最大空闲连接
        min-idle: 0 #最小空闲连接
        max-wait: 100ms #连接等待时间
  cloud:
    nacos:
      server-addr: localhost:8848 #nacos 服务地址
      discovery:
        enabled: true #关闭nacos发现，用于调试
    sentinel:
      eager: true
      transport:
        dashboard: localhost:7010 #sentinel控制台


#feign支持sentinel
feign:
  sentinel:
    enabled: true

#自定义配置
my-config:
  enable-mq: true