
spring:
  mvc:
    hiddenmethod:
      filter:
        enabled: true
  cloud:
    nacos:
      server-addr: localhost:8848 #nacos 服务地址
      discovery:
        enabled: true #关闭nacos发现，用于调试
    sentinel:
      eager: true
      transport:
        dashboard: localhost:7010 #sentinel控制台


#feign支持sentinel
feign:
  sentinel:
    enabled: true

#自定义配置
my-config:
  enable-mq: true