
spring:
  mvc:
    hiddenmethod:
      filter:
        enabled: true
  cloud:
    sentinel:
      eager: true
      transport:
        dashboard: localhost:7010 #sentinel控制台


#feign支持sentinel
feign:
  sentinel:
    enabled: true

#自定义配置
my-config:
  enable-mq: true

minio:
  endpoint: http://43.136.68.91:9090
  accessKey: minio123
  secretKey: minio123
  bucket: 555