
server:
  port: 8080

spring:
  config:
    activate:
      on-profile:
        - dev
  rabbitmq:
    virtual-host: /acimage
    host: 192.168.130.128
    port: 5672
    username: acimage
    password: acimage
    listener:
      simple:
        auto-startup: false #消费者是否自动启动
      direct:
        auto-startup: false #生产者是否自动启动
  datasource:
    url: jdbc:mysql://localhost:3306/acimage_community?useSSl=false&allowMultiQueries=true&serverTimezone=UTC
    username: root
    password: mysql
  redis:
    host: 192.168.130.128
    port: 6379
    password: redis
    lettuce:
      pool:
        max-active: 8
        max-idle: 8 #最大空闲连接
        min-idle: 0 #最小空闲连接
        max-wait: 100ms #连接等待时间
  cloud:
    nacos:
      server-addr: localhost:8848 #nacos 服务地址