
spring:
  profiles:
    include: common,qiniu
    active: dev2
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 55MB
  application:
    name: community-service #服务名称
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver



mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.acimage.common.model.domain,com.acimage.community.model.domain
  configuration:
    map-underscore-to-camel-case: true
#    log-impl: org.apache.ibatis.logging.slf4j.Slf4jImpl
  global-config:
    db-config:
      table-prefix: tb_

feign:
  okhttp:
    enabled: true
  httpclient:
    max-connections: 20 # 最大的连接数
    max-connections-per-route: 5 # 每个路径的最大连接数





